# Generated by Django 3.0.8 on 2020-07-28 00:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LotSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('lot_size_low', models.IntegerField()),
                ('lot_size_high', models.IntegerField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('tier_range_low', models.IntegerField()),
                ('tier_range_high', models.IntegerField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=2)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('counties', models.ManyToManyField(blank=True, related_name='statecounties', to='api.County')),
            ],
        ),
        migrations.AddField(
            model_name='county',
            name='lot_sizes',
            field=models.ManyToManyField(blank=True, related_name='countylots', to='api.LotSize'),
        ),
        migrations.AddField(
            model_name='county',
            name='service_charges',
            field=models.ManyToManyField(blank=True, related_name='countycharges', to='billing.Charge'),
        ),
        migrations.AddField(
            model_name='county',
            name='tier_ranges',
            field=models.ManyToManyField(blank=True, related_name='countytiers', to='api.Tier'),
        ),
    ]
