# Generated by Django 3.0.8 on 2020-08-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hcf_usage',
        ),
    ]
