# Generated by Django 3.0.8 on 2020-08-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='charges',
            field=models.ManyToManyField(blank=True, related_name='charges', to='billing.Charge'),
        ),
    ]
